[project]
name = "glom-io-transform-release"
version = "2.0.0"

[tool.setuptools]
packages = [
"glom_io_transform",
"glom_io_transform.analysis",
"glom_io_transform.analysis.compute",
"glom_io_transform.analysis.figures",
"glom_io_transform.model_fitting",
"glom_io_transform.model_fitting.conn_models",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

